sudo: required
services:
  - docker

before_install:
  - docker build -t gavanyung/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run gavanyung/react-test npm test -- --coverage

after_success:
  - docker build -t gavanyung/multi-client ./client
  - docker build -t gavanyung/multi-nginx ./nginx
  - docker build -t gavanyung/multi-server ./server
  - docker build -t gavanyung/multi-worker ./worker
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to docker hub
  - docker push gavanyung/multi-client
  - docker push gavanyung/multi-nginx
  - docker push gavanyung/multi-server
  - docker push gavanyung/multi-worker
